spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:api_restaurante}?currentSchema=restaurante
    username: ${DB_USERNAME:robin}
    password: ${DB_PASSWORD:1095827105}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hibernate.default_schema: restaurante

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: restaurante
    default-schema: restaurante

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:c3VwZXItc2VjcmV0LWtleS1mb3ItYXBpLXJlc3RhdXJhbnRlLTIwMjY=}
  expiration: ${JWT_EXPIRATION:86400000}
